name: Nuget Build 

on:
  push:
    branches: [ "main" ]
  
jobs:
  nuget:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source "https://nuget.pkg.github.com/thudugala/index.json" --name "GitHub" --username thudugala --password ${{ secrets.Elvin_Package_Registry }}

    - name: Restore dependencies
      run: dotnet restore "Thudugala.MultiCurrencyMoney/Thudugala.MultiCurrencyMoney.sln"

    - name: Build
      run: dotnet build "Thudugala.MultiCurrencyMoney/Thudugala.MultiCurrencyMoney.sln" --no-restore --configuration Release
   
    - uses: actions/upload-artifact@v4.3.0
      with:
          name: Thudugala.MultiCurrencyMoney
          path: Thudugala.MultiCurrencyMoney/Thudugala.MultiCurrencyMoney/bin/Release/ 

    - name: Push generated package to GitHub registry
      run: dotnet nuget push **/*.nupkg --source "GitHub" --skip-duplicate
      
      
